console.log('Loading express...');
require('express');
console.log('Loading cors...');
require('cors');
console.log('Loading dotenv...');
require('dotenv');
console.log('Loading express-session...');
require('express-session');
console.log('Loading passport...');
require('passport');
console.log('Done');
